import fs from 'fs';
import path from 'path';

const packageJson = require('../package.json');

const versionFileContent = `// This file is auto generated by npm run version
export default '${packageJson.version}';
`;

fs.writeFileSync(path.join(__dirname, '../src/version.ts'), versionFileContent, 'utf8');
